export const TEST = 'TEST';
export const SET_ADMIN = 'SET_ADMIN';
//patients
export const SET_PATIENTS = 'SET_PATIENTS';
export const SET_SELECTED_PATIENT = 'SET_SELECTED_PATIENT';
export const SET_PATIENT_MEDICAL_HISTORY = 'SET_PATIENT_MEDICAL_HISTORY';
export const SET_PATIENT_MEDICATION_HISTORY = 'SET_PATIENT_MEDICATION_HISTORY';
export const SET_PATIENT_SOAP = 'SET_PATIENT_SOAP';
export const SET_PATIENT_LAB_TEST = 'SET_PATIENT_LAB_TEST';
export const SET_PATIENT_VITAL_SIGNS = 'SET_PATIENT_VITAL_SIGNS';
//staff
export const SET_STAFFS = 'SET_STAFFS';
export const SET_SELECTED_STAFF = 'SET_SELECTED_STAFF';
//pharmacy
export const SET_PHARMACY = 'SET_PHARMACY';
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const SET_PHARMACY_STATE = 'SET_PHARMACY_STATE';
export const SET_SELECTED_PRODUCT = 'SET_SELECTED_PRODUCT';
export const SET_ORDERS = 'SET_ORDERS';
export const SET_SELECTED_ORDER = 'SET_SELECTED_ORDER';
export const SET_LOGISTICS = 'SET_LOGISTICS';
export const SET_SELECTED_LOGISTICS = 'SET_SELECTED_LOGISTICS';
